ERROR 2025-07-31 23:01:22,099 log Internal Server Error: /login/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\login_views.py", line 46, in doctor_login_view
    return redirect('doctor_dashboard')  # Doktor dashboard'una yönlendir
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\shortcuts.py", line 130, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'doctor_dashboard' not found. 'doctor_dashboard' is not a valid view function or pattern name.
ERROR 2025-07-31 23:01:22,118 basehttp "POST /login/doctor/ HTTP/1.1" 500 89314
ERROR 2025-07-31 23:06:24,071 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 7, in doctor_dashboard_view
    return render(request, 'dashboard/doctor_dashboard.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashboard/doctor_dashboard.html
ERROR 2025-07-31 23:06:24,075 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 82656
ERROR 2025-07-31 23:08:01,722 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 7, in doctor_dashboard_view
    return render(request, 'doctor_dashboard.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'doctor_logout' not found. 'doctor_logout' is not a valid view function or pattern name.
ERROR 2025-07-31 23:08:01,735 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 162032
ERROR 2025-07-31 23:10:27,658 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 23, in doctor_dashboard_view
    return render(request, 'doctor_login.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: doctor_login.html
ERROR 2025-07-31 23:10:27,664 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 82850
ERROR 2025-07-31 23:10:56,378 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 23, in doctor_dashboard_view
    return render(request, 'doctor_login.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: doctor_login.html
ERROR 2025-07-31 23:10:56,381 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 82850
ERROR 2025-08-19 18:25:07,600 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 18, in doctor_dashboard_view
    return render(request, 'doctor_dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 212, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-08-19 18:25:07,616 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 174995
ERROR 2025-08-19 18:25:16,052 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 18, in doctor_dashboard_view
    return render(request, 'doctor_dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 212, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-08-19 18:25:16,054 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 174995
ERROR 2025-08-19 18:25:17,398 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 18, in doctor_dashboard_view
    return render(request, 'doctor_dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 212, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-08-19 18:25:17,401 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 174995
ERROR 2025-08-19 18:25:19,804 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 18, in doctor_dashboard_view
    return render(request, 'doctor_dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 212, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR 2025-08-19 18:25:19,810 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 175023
ERROR 2025-08-19 18:33:41,842 log Internal Server Error: /dashboard/doctor/
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "request.path.endswith('/prescriptions/new/')"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\hastane\views\doctor_dashboard_view.py", line 18, in doctor_dashboard_view
    return render(request, 'doctor_dashboard.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\defaulttags.py", line 967, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\defaulttags.py", line 900, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\defaulttags.py", line 903, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\HastaneYonetim\HastaneYonetimProjesi\venv\Lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('/prescriptions/new/')' from 'request.path.endswith('/prescriptions/new/')'
ERROR 2025-08-19 18:33:41,856 basehttp "GET /dashboard/doctor/ HTTP/1.1" 500 199122
